@echo off
echo Launching Chrome with remote debugging on port 9222...
"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir="C:\chrome-debug" --profile-directory="Profile 1"